apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../../components/schemas/clickhouse/overlays/standard/users
  - secrets.yaml

patches:
  - target:
      kind: AtlasSchema
      name: users
    path: patch-users.yaml
