apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: COMPONENT_NAME
spec:
  schedule: "* * * * *"
  concurrencyPolicy: "Forbid"
  startingDeadlineSeconds: 0
  workflowSpec:
    entrypoint: COMPONENT_NAME
    templates:
    - name: COMPONENT_NAME
      container:
        image: image-name
