apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../../components/cron_workflow/overlays/invoices

patches:
  - target:
      kind: CronWorkflow
      name: invoices-dataflow-dbt
    path: dag.yaml
  - target:
      kind: CronWorkflow
      name: invoices-dataflow-dbt
    path: env.yaml
