apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

commonLabels:
  app: hello-cron-wf

patches:
  - target:
      kind: CronWorkflow
      name: COMPONENT_NAME
    patch: |-
      - op: replace
        path: /metadata/name
        value: hello-cron-wf
      - op: replace
        path: /spec/workflowSpec/templates/0/dag/tasks/0/name
        value: hello-cron-wf
      - op: replace
        path: /spec/workflowSpec/templates/0/dag/tasks/0/template
        value: hello-cron-wf
      - op: replace
        path: /spec/workflowSpec/templates/1/name
        value: hello-cron-wf
