apiVersion: apps/v1
kind: Deployment
metadata:
  name: COMPONENT_NAME
spec:
  template:
    spec:
      serviceAccountName: SERVICE_ACCOUNT_NAME
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: topology.gke.io/zone
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: COMPONENT_NAME
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - COMPONENT_NAME
              topologyKey: "kubernetes.io/hostname"
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: cloud.google.com/gke-nodepool
                    operator: In
                    values:
                      - prometheus
      containers:
        - name: COMPONENT_NAME
          image: image-name
          args:
            - "--web.listen-address=:9090"
          ports:
            - name: web
              containerPort: 9090
          readinessProbe:
            httpGet:
              path: /-/ready
              port: web
          livenessProbe:
            httpGet:
              path: /-/healthy
              port: web
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - all
            privileged: false
            runAsGroup: 1000
            runAsNonRoot: true
            runAsUser: 1000
