- op: add
  path: /spec/configuration/users
  value:
    admin/k8s_secret_password: clickhouse/chi-users/ADMIN
    admin/profile: admin
    admin/quota: default
    admin/access_management: 1
    admin/networks/ip:
     - ::1
     - 127.0.0.1/32
     - 172.0.0.0/8
     - 10.0.0.0/8
    operator/k8s_secret_password: clickhouse/chi-users/OPERATOR
    operator/profile: default
    operator/quota: default
    operator/networks/ip:
     - ::1
     - 127.0.0.1/32
     - 172.0.0.0/8
     - 10.0.0.0/8
    grafana/k8s_secret_password: clickhouse/chi-users/GRAFANA
    grafana/profile: default
    grafana/quota: default
    grafana/networks/ip:
     - ::1
     - 127.0.0.1/32
     - 172.0.0.0/8
     - 10.0.0.0/8

- op: add
  path: /spec/configuration/profiles
  value:
    admin/os_thread_priority: 2
    admin/log_queries: 1
    admin/async_insert: 1
    admin/wait_for_async_insert: 1
    admin/async_insert_deduplicate: 1
    default/os_thread_priority: 4
    default/log_queries: 1
    default/async_insert: 1
    default/wait_for_async_insert: 1
    default/async_insert_deduplicate: 1
    engineer/os_thread_priority: 1
    engineer/log_queries: 1
    engineer/async_insert: 1
    engineer/wait_for_async_insert: 1
    engineer/async_insert_deduplicate: 1
    metabase/os_thread_priority: 10
    metabase/log_queries: 1
    microservice/os_thread_priority: 2
    microservice/log_queries: 1
    microservice/async_insert: 1
    microservice/wait_for_async_insert: 1
    microservice/async_insert_deduplicate: 1
    dbt/os_thread_priority: 2
    dbt/log_queries: 1
    dbt/async_insert: 1
    dbt/wait_for_async_insert: 1
    dbt/async_insert_deduplicate: 1

- op: add
  path: /spec/configuration/settings
  value:
    max_connections: 10240
    distributed_ddl/path: /etc/clickhouse-server/new_task_queue/ddl
    profile/dbt/distributed_product_mode: allow

- op: replace
  path: /spec/configuration/clusters/0/templates/dataVolumeClaimTemplate
  value: ""

- op: add
  path: /spec/templates/volumeClaimTemplates
  value:
    - name: chi-standard-shard-0-replica-0
      spec:
        volumeName: chi-standard-shard-0-replica-0
    - name: chi-standard-shard-1-replica-0
      spec:
        volumeName: chi-standard-shard-1-replica-0

- op: replace
  path: /spec/configuration/clusters/0/layout
  value:
    shards:
      - name: shard-0
        replicasCount: 1
        templates:
          dataVolumeClaimTemplate: chi-standard-shard-0-replica-0
      - name: shard-1
        replicasCount: 1
        templates:
          dataVolumeClaimTemplate: chi-standard-shard-1-replica-0

- op: add
  path: /spec/configuration/clusters/0/zookeeper
  value:
    nodes:
      - host: chk.clickhouse-keeper.svc.cluster.local
        port: 2181
