- op: add
  path: /spec/configuration/users
  value:
    admin/k8s_secret_password: clickhouse/chi-users/ADMIN
    admin/profile: admin
    admin/quota: default
    admin/networks/ip:
      - "10.0.0.0/8"
      - "192.168.0.0/16"
      - "127.0.0.1/32"
    admin/access_management: 1
