- op: add
  path: /spec/configuration/users
  value:
    admin/k8s_secret_password: clickhouse/chi-users/ADMIN
    admin/profile: admin
    admin/quota: default
    admin/networks/ip:
      - "192.168.0.0/16"
      - "127.0.0.1/32"
    admin/access_management: 1
    invoice_svc/k8s_secret_password: clickhouse/chi-users/INVOICE_SVC
    invoice_svc/profile: microservice
    invoice_svc/quota: default
    invoice_svc/networks/ip:
      - "192.168.0.0/16"
      - "127.0.0.1/32"
    invoice_svc/allow_databases/database:
      - "invoices"
      - "sellers"
      - "marts"
