- op: add
  path: /spec/configuration/users
  value:
    admin/k8s_secret_password: clickhouse/chi-users/ADMIN
    admin/profile: admin
    admin/quota: default
    admin/access_management: 1
    admin/networks/ip:
     - ::1
     - 127.0.0.1/32
     - 172.0.0.0/8
     - 10.0.0.0/8
    operator/k8s_secret_password: clickhouse/chi-users/OPERATOR
    operator/profile: default
    operator/quota: default
    operator/networks/ip:
     - ::1
     - 127.0.0.1/32
     - 172.0.0.0/8
     - 10.0.0.0/8
    grafana/k8s_secret_password: clickhouse/chi-users/GRAFANA
    grafana/profile: default
    grafana/quota: default
    grafana/networks/ip:
     - ::1
     - 127.0.0.1/32
     - 172.0.0.0/8
     - 10.0.0.0/8

- op: replace
  path: /spec/configuration/clusters/0/layout/shardsCount
  value: 2

- op: replace
  path: /spec/configuration/clusters/0/layout/replicasCount
  value: 1

- op: add
  path: /spec/configuration/zookeeper
  value:
    nodes:
      - host: chk-0
        port: 2181
