- op: add
  path: /spec/configuration/users
  value:
    admin/k8s_secret_password: clickhouse/chi-users/ADMIN
    admin/profile: admin
    admin/quota: default
    admin/networks/ip:
      - "192.168.0.0/16"
      - "127.0.0.1/32"
    admin/access_management: 1
    admin/allow_databases/database:
      - "default"
      - "invoices"
    eric/k8s_secret_password: clickhouse/chi-users/ERIC
    eric/profile: engineer
    eric/quota: default
    eric/networks/ip:
      - "192.168.0.0/18"
      - "127.0.0.1/32"
    eric/allow_databases/database:
      - "invoices"
