- op: add
  path: /spec/taskID
  value: standard-cluster

# - op: add
#   path: /spec/configuration/clusters/0/zookeeper
#   value:
#     nodes:
#       - host: chk.clickhouse-keeper.svc.cluster.local
#         port: 2181

- op: add
  path: /spec/configuration/users
  value:
    admin/k8s_secret_password: clickhouse/chi-users/ADMIN
    admin/profile: admin
    admin/quota: default
    admin/access_management: 1
    admin/named_collection_control: 1
    admin/networks/ip:
     - ::1
     - 127.0.0.1/32
     - 172.0.0.0/8
     - 10.0.0.0/8
    operator/k8s_secret_password: clickhouse/chi-users/OPERATOR
    operator/profile: default
    operator/quota: default
    operator/networks/ip:
     - ::1
     - 127.0.0.1/32
     - 172.0.0.0/8
     - 10.0.0.0/8
    grafana/k8s_secret_password: clickhouse/chi-users/GRAFANA
    grafana/profile: default
    grafana/quota: default
    grafana/networks/ip:
     - ::1
     - 127.0.0.1/32
     - 172.0.0.0/8
     - 10.0.0.0/8

- op: add
  path: /spec/configuration/profiles
  value:
    admin/os_thread_priority: 2
    admin/log_queries: 1
    admin/async_insert: 1
    admin/wait_for_async_insert: 1
    admin/async_insert_deduplicate: 1
    admin/distributed_product_mode: global
    default/os_thread_priority: 4
    default/log_queries: 1
    default/async_insert: 1
    default/wait_for_async_insert: 1
    default/async_insert_deduplicate: 1
    engineer/os_thread_priority: 1
    engineer/log_queries: 1
    engineer/async_insert: 1
    engineer/wait_for_async_insert: 1
    engineer/async_insert_deduplicate: 1
    metabase/os_thread_priority: 10
    metabase/log_queries: 1
    microservice/os_thread_priority: 2
    microservice/log_queries: 1
    microservice/async_insert: 1
    microservice/wait_for_async_insert: 1
    microservice/async_insert_deduplicate: 1
    dbt/os_thread_priority: 2
    dbt/log_queries: 1
    dbt/async_insert: 1
    dbt/wait_for_async_insert: 1
    dbt/async_insert_deduplicate: 1
    dbt/distributed_product_mode: global

- op: add
  path: /spec/configuration/settings
  value:
    max_connections: 10240
    distributed_ddl/path: /etc/clickhouse-server/new_task_queue/ddl

- op: add
  path: /spec/configuration/files
  value:
    config.d/named_collections.xml: |
      PGNsaWNraG91c2U+CiAgICAgICAgICA8bmFtZWRfY29sbGVjdGlvbnM+CiAgICAgICAgICAgICAgPG15c3FsX21lbWJlcl9zdmM+CiAgICAgICAgICAgICAgICAgIDx1c2VyIG92ZXJyaWRhYmxlPWZhbHNlPm1lbWJlcl9zdmM8L3VzZXI+CiAgICAgICAgICAgICAgICAgIDxwYXNzd29yZCBvdmVycmlkYWJsZT1mYWxzZT4xMjM0NTY8L3Bhc3N3b3JkPgogICAgICAgICAgICAgICAgICA8aG9zdCBvdmVycmlkYWJsZT1mYWxzZT4xMjcuMC4wLjE8L2hvc3Q+CiAgICAgICAgICAgICAgICAgIDxwb3J0IG92ZXJyaWRhYmxlPWZhbHNlPjMzMDY8L3BvcnQ+CiAgICAgICAgICAgICAgICAgIDxkYXRhYmFzZSBvdmVycmlkYWJsZT1mYWxzZT5tZW1iZXJfc3ZjPC9kYXRhYmFzZT4KICAgICAgICAgICAgICA8L215c3FsX21lbWJlcl9zdmM+CiAgICAgICAgICA8L25hbWVkX2NvbGxlY3Rpb25zPgogICAgICA8L2NsaWNraG91c2U+

- op: replace
  path: /spec/configuration/clusters/0/templates/dataVolumeClaimTemplate
  value: ""

- op: add
  path: /spec/templates/volumeClaimTemplates
  value:
    - name: chi-standard-0-0
      spec:
        storageClassName: chi-data
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
        reclaimPolicy: Retain
        
- op: replace
  path: /spec/configuration/clusters/0/layout
  value:
    shards:
      - name: shard-0
        replicasCount: 1
        templates:
          dataVolumeClaimTemplate: chi-standard-0-0

- op: replace
  path: /spec/templates/podTemplates/0/spec/containers/0/resources
  value:
    limit:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 1Gi
