apiVersion: v1
kind: PersistentVolume
metadata:
 name: chi-standard-shard-0-replica-0
spec:
  storageClassName: chi-data
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
