---
apiVersion: v1
kind: PersistentVolume
metadata:
 name: chi-standard-shard-0-replica-0
spec:
  storageClassName: chi-data
  accessModes:
      - ReadWriteOnce
  resources:
      requests:
        storage: 1Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
 name: chi-standard-shard-1-replica-0
spec:
  storageClassName: chi-data
  accessModes:
      - ReadWriteOnce
  resources:
      requests:
        storage: 1Mi
