apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: COMPONENT_NAME
spec:
  defaults:
    templates:
      serviceTemplate: service-template
      podTemplate: pod-template
  configuration:
    clusters:
      - name: standard
        layout:
          shardsCount: 1
          replicasCount: 1
  templates:
    podTemplates:
      - name: pod-template
        spec:
          topologySpreadConstraints:
          - maxSkew: 1
            topologyKey: topology.gke.io/zone
            whenUnsatisfiable: DoNotSchedule
            labelSelector:
              matchLabels:
                app: COMPONENT_NAME
          affinity:
            podAntiAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 1
                podAffinityTerm:
                  labelSelector:
                    matchExpressions:
                    - key: app
                      operator: In
                      values:
                      - clickhouse
                  topologyKey: "kubernetes.io/hostname"
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: cloud.google.com/gke-nodepool
                        operator: In
                        values:
                          - clickhouse
          containers:
            - name: clickhouse
              image: image-name
              imagePullPolicy: IfNotPresent
              volumeMounts:
                - name: data-storage
                  mountPath: /var/lib/clickhouse
              resources:
                limit:
                  cpu: 500m
                  memory: 1Gi
                requests:
                  cpu: 500m
                  memory: 1Gi
              volumes:
                - name: data-storage
                  persistentVolumeClaim:
                    claimName: nfs-server
    serviceTemplates:
      - name: service-template
        generateName: "chendpoint-{chi}"
        spec:
          ports:
          - name: http
            port: 8123
          - name: tcp
            port: 9000
          type: ClusterIP
          ClusterIP: None
