apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configurations:
  - images-transformer.yaml

resources:
  - ../../../../components/cron_workflow/overlays/hello_cron_wf

images:
  - name: image-name
    newName: alpine
    newTag: "3.6"

patches:
  - target:
      kind: CronWorkflow
      name: hello-cron-wf
    path: patch-hello-cron-wf.yaml


