apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

commonLabels:
  app: nfs-server

patches:
  - target:
      kind: Deployment
      name: COMPONENT_NAME
    patch: |-
      - op: replace
        path: /metadata/name
        value: nfs-server
      - op: replace
        path: /spec/template/spec/containers/0/name
        value: nfs-server
      - op: replace
        path: /spec/template/spec/containers/0/volumeMounts/0/name
        value: nfs-server
      - op: replace
        path: /spec/template/spec/volumes/0/name
        value: nfs-server
      - op: replace
        path: /spec/template/spec/volumes/0/persistentVolumeClaim/claimName
        value: nfs-server
  - target:
      kind: Service
      name: COMPONENT_NAME
    patch: |-
      - op: replace
        path: /metadata/name
        value: nfs-server
  - target:
      kind: PersistentVolumeClaim
      name: COMPONENT_NAME
    patch: |-
      - op: replace
        path: /metadata/name
        value: nfs-server
