- op: replace
  path: /spec/replicas
  value: 1

- op: replace
  path: /spec/template/spec/containers/0/resources
  value:
    requests:
      memory: "256M"
      cpu: "500m"
    limits:
      memory: "256M"
      cpu: "500m"

