apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# resources:
#   - ./install.yaml

commonLabels:
  app: chk

images:
  - name: image-name
    newName: clickhouse/clickhouse-keeper
    newTag: "24.2"

patches:
  - target:
      kind: StatefulSet
      name: chk
    path: clickhouse-keeper.yaml
