apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infrastructure
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/zhweiliu/infrastructure.git
      revision: main
      directories:
      - path: argocd/clusters/infrastructure/*
  template:
    metadata:
      name: 'infrastructure-{{path.basename}}'
    spec:
      project: "default"
      source:
        repoURL: https://github.com/zhweiliu/infrastructure.git
        targetRevision: main
        path: argocd/clusters/infrastructure/{{path.basename}}
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        automated: 
          prune: true
          allowEmpty: true
        syncOptions:
        - CreateNamespace=true
        - ServerSideApply=true
